## MSCA 37014  Python for Analytics
### Assignment#1 (100 Points)
Please submit your assignment solutions in **pdf** or **html** file

#### Question 1. Use both arange() and linspace() functions to create a range from 0 to 34 (34 not included) with 3 as the step; then use the range to create 3x4 matrix; Convert all the numbers to integers (5 points)

In [137]:
import numpy as np

In [4]:
n = np.arange(0,34,3,dtype=float)
n

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33.])

In [5]:
n = np.linspace(0,33,12)
n

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33.])

In [6]:
# Your Solution:
n = n.reshape(3,4)
n

array([[ 0.,  3.,  6.,  9.],
       [12., 15., 18., 21.],
       [24., 27., 30., 33.]])

In [12]:
# Your Solution:
n = n.astype(int)

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [11]:
# Your Solution:
list_1 = list(range(0,34,3))
list_1 = np.array(list_1)
list_1 = list_1.reshape(3,4)
list_1

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

#### Question 2. Create an 4x4 array of the random samples from a uniform distribution over [0, 1) (5 points)

In [16]:
import numpy as np
np.random.seed(1234)
np.random.uniform(0,1,(4,4))

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858],
       [0.77997581, 0.27259261, 0.27646426, 0.80187218],
       [0.95813935, 0.87593263, 0.35781727, 0.50099513],
       [0.68346294, 0.71270203, 0.37025075, 0.56119619]])

#### Question 3. Create an 4x4 array of the random samples from a "standard normal" distribution (5 points)

In [17]:
import numpy as np 
np.random.seed(1235)
np.random.randn(4,4)

array([[ 0.68938232, -0.03171215,  0.66805361,  0.48883782],
       [-0.67978825, -1.30747938,  1.47030437, -1.23102724],
       [ 0.95877525,  0.74048962,  0.70329051, -0.07352256],
       [-1.27431351, -0.23115703,  0.50514333,  0.51273198]])

#### Question 4. Use the two arrays from Questions 2 and 3 to perform addition, subtraction, multiplication, and division. (5 point)

In [19]:
np.random.seed(1235)
# Your Solution - addition:
a1 = np.random.uniform(0,1,(4,4)) 
a2 = np.random.randn(4,4)
a1 + a2

array([[-0.32055092,  0.76096944,  0.98474625,  1.45613884],
       [ 2.05313528,  1.57061221, -0.28987643,  0.96947004],
       [-0.30834613,  0.99141845, -0.63227552,  0.07763483],
       [-2.16004789,  1.44000386,  2.42556437,  0.20875181]])

In [20]:
np.random.seed(1235)
# Your Solution - subtraction:
a1 - a2

array([[ 2.22807609,  1.2232835 , -0.0255404 ,  0.43067488],
       [-0.55558522,  0.10934769,  0.77433514, -0.23751168],
       [ 1.05233535,  0.31435364,  2.05580039,  1.47073906],
       [ 3.06829151,  0.43770483, -0.51072537,  0.24237106]])

In [21]:
np.random.seed(1235)
# Your Solution - multiplication:
a1 * a2

array([[-1.21539254, -0.22933701,  0.24226822,  0.48371487],
       [ 0.97667239,  0.61371645, -0.12889164,  0.22086509],
       [-0.25308309,  0.22102308, -0.95663573, -0.53926155],
       [-1.18715147,  0.4705064 ,  1.40563052, -0.0037916 ]])

In [22]:
np.random.seed(1235)
# Your Solution - division:
a1 / a2

array([[ -0.74845207,  -4.29200218,   0.94943929,   1.83996102],
       [  0.57405539,   1.14966173,  -0.45522782,   0.60643699],
       [ -0.54677691,   1.92857769,  -0.52957019,  -1.11145588],
       [ -0.1737155 ,   1.87340169,   0.65212877, -13.41859033]])

#### Question 5. Use the 3x3 array to do the following: (Hint: Refer to Lecture Notes) (10 Point)

arr33 = np.array(([5,10,15],[15,25,40],[35,30,25]))

1) Index array([15, 25, 40]) (2.5 points)

2) Index the element of 30 (2.5 points)

3) Index (2,2) array from top right corner (2.5 points)

4) Index the bottom row (2.5 points)

In [23]:
arr33 = np.array(([5,10,15],[15,25,40],[35,30,25]))
# Your Solution 1):
arr33[1]

array([15, 25, 40])

In [24]:
# Your Solution 2):
arr33[2][1]

30

In [55]:
# Your Solution 3):
arr33[:-1, 1:]

array([[10, 15],
       [25, 40]])

In [27]:
# Your Solution 4):
arr33[-1]

array([35, 30, 25])

#### Question 6. Use np.random.randint(0,50,25) (5 Points)

1) Reshape this one dimensional array to a 5x5 array; (2.5 points)

2) Use the output from 1) to make an one dimentional array.  (2.5 points)

In [57]:
np.random.seed(1235)
# Your Solution 1):
n = np.random.randint(0,50,25)
n = n.reshape(5,5)

array([[11, 34,  2, 47,  3],
       [ 7, 35, 40, 16, 16],
       [ 2, 15, 20, 14, 38],
       [40, 35, 15, 11, 31],
       [46, 30,  5, 12, 37]])

In [58]:
# Your Solution 2):
n[::]

array([11, 34,  2, 47,  3,  7, 35, 40, 16, 16,  2, 15, 20, 14, 38, 40, 35,
       15, 11, 31, 46, 30,  5, 12, 37])

#### Question 7. Use the array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]) and b = np.array([[10, 11, 12]]) (5 Points)

1) Use vstack() and hstack() to stack a and b vertically and horizontally

2) Use concatenate() funtion to stack a and b vertically and horizontally

In [60]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12]])
# Your Solution 1):
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
# Your Solution 1):
np.hstack((a,b.T))

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [63]:
# Your Solution 2):
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
# Your Solution 2):
np.concatenate((a,b.T),axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

#### Question 8. Use Numpy to import WCFrequency data (10 Points)
(Please review the updated 4.6 Lecture notes)

1) View the top few records (2.5 points)

2) View the bottom 5 records (2.5 points)

3) View the entire file (5 points)

In [65]:
import os 
import csv

# Your Solution 1):
os.chdir(r'/Users/nimo/Desktop/python/Data')
with open('WCFrequency.csv','r') as f:
    data = list(csv.reader(f, delimiter = ','))
data[:5]

[['class', 'year', 'payroll', 'claimcount'],
 ['1', '1', '32.321999', '1'],
 ['1', '2', '33.778999', '4'],
 ['1', '3', '43.548', '3'],
 ['1', '4', '46.686001', '5']]

In [66]:
# Your Solution 2):
data[-5:]

# or 
np.genfromtxt('WCFrequency.csv', delimiter=',', dtype='<U16',autostrip=True)[-5:]

[['133', '3', '69.913002', '0'],
 ['133', '4', '46.289001', '0'],
 ['133', '5', '91.119003', '0'],
 ['133', '6', '78.456001', '1'],
 ['133', '7', '84.362', '2']]

In [67]:
# Your Solution 3):
data

# or 
np.genfromtxt('WCFrequency.csv', delimiter=',', dtype='<U16',autostrip=True)

[['class', 'year', 'payroll', 'claimcount'],
 ['1', '1', '32.321999', '1'],
 ['1', '2', '33.778999', '4'],
 ['1', '3', '43.548', '3'],
 ['1', '4', '46.686001', '5'],
 ['1', '5', '34.713001', '1'],
 ['1', '6', '32.856998', '3'],
 ['1', '7', '36.599998', '4'],
 ['2', '1', '45.994999', '3'],
 ['2', '2', '37.888', '1'],
 ['2', '3', '34.581001', '0'],
 ['2', '4', '28.298', '0'],
 ['2', '5', '45.264999', '2'],
 ['2', '6', '39.945', '0'],
 ['2', '7', '39.321999', '4'],
 ['3', '1', '289.047', '5'],
 ['3', '2', '392.17599', '8'],
 ['3', '3', '368.98199', '8'],
 ['3', '4', '323.76999', '8'],
 ['3', '5', '385.22198', '16'],
 ['3', '6', '346.39001', '8'],
 ['3', '7', '324.13199', '9'],
 ['4', '1', '0', '0'],
 ['4', '2', '0', '0'],
 ['4', '3', '0', '0'],
 ['4', '4', '0.037', '0'],
 ['4', '5', '0', '0'],
 ['4', '6', '0', '0'],
 ['4', '7', '0', '0'],
 ['5', '1', '310.38901', '15'],
 ['5', '2', '292.46399', '10'],
 ['5', '3', '262.56', '18'],
 ['5', '4', '273.25699', '25'],
 ['5', '5', '372.73001', '2

#### Question 9. Use the following array to find all values less than 0.5 and greater than 0.1 (5 points)

twentyfive_vals = np.random.random((25,))

In [72]:
np.random.seed(1235)
twentyfive_vals = np.random.random((25,))
# Your Solution:
condition = (0.1 < twentyfive_vals) & (twentyfive_vals < 0.5)
twentyfive_vals[condition]

array([0.47960292, 0.24222936, 0.36597918, 0.37199461, 0.45412181,
       0.22556144, 0.44132418, 0.1765342 , 0.17411005])

### Numpy Indexing and Selection: 

#### Question 10. Now you will be given a matrix mat and be asked to replicate the resulting matrix outputs (10 points)

In [84]:
mat = np.arange(1,26)
# Your Solution:
mat_1 = mat.reshape(5,5)
mat_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
# Your Solution:
mat_1[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [87]:
# Your Solution:
mat[19]

# or 
mat_1[3][-1]

20

In [95]:
# Your Solution:
mat_1[:,[1]][:-2]

array([[ 2],
       [ 7],
       [12]])

In [96]:
# Your Solution:
mat_1[-1]

array([21, 22, 23, 24, 25])

In [97]:
# Your Solution:
mat[-5:]

array([21, 22, 23, 24, 25])

In [98]:
# Your Solution:
mat_1[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Questions 11. Swap the first column with the last column (5 points)
arr_2dm = np.array(([2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]))
arr_2dm

In [99]:
arr_2dm = np.array(([2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]))
arr_2dm

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [106]:
# Your Solution:
last = arr_2dm[:,[-1]]
first = arr_2dm[:,[0]]
rest = arr_2dm[:,[1,-2]]
np.concatenate((last,rest,first),axis=1)

array([[ 8,  4,  6,  2],
       [16, 12, 14, 10],
       [24, 20, 22, 18],
       [32, 28, 30, 26]])

#### Question 12. Create a 3x3 matrix with values ranging from 0 to 8 (5 points)¶

In [109]:
# Your Solution:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  Question 13. Create a new completely independent object B copied from A (so-called "deep copy") (5 points)

A = np.array([[1, 2], [3, 4]])

In [110]:
A = np.array([[1, 2], [3, 4]])
# Your Solution:
B = np.copy(A)
B

array([[1, 2],
       [3, 4]])

#### Question 14. How to get the positions where elements of two arrays match? (5 points)

In [138]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [144]:
# Your Solution:
result = np.where(a == b) 
result

(array([1, 3, 5, 7]),)

#### Question 15. How to extract the desired numbers below between a given range (a>=6)&(a<=10) from a numpy array? (5 points)

In [125]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [126]:
# Your Solution:
a[(a>=6)&(a<=10)]

array([ 6,  9, 10])

#### Question 16. Find the mean, median, standard deviation of iris's sepal length (1st column) (5 points)

In [127]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [128]:
# Your Solution:
np.mean(sepallength)

5.843333333333334

In [129]:
# Your Solution:
np.median(sepallength)

5.8

In [130]:
# Your Solution:
np.std(sepallength)

0.8253012917851409

#### Question 17. Mapping two lists to a dictionary: (5 points)
keys = ["a", "b", "c"]

values = [1, 2, 3]

In [134]:
keys = ["a", "b", "c"]
values = [1, 2, 3]
# Your Solution:
dictionary = dict(zip(keys, values))
dictionary

{'a': 1, 'b': 2, 'c': 3}